name: Run azd hooks
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: templateName
    displayName: Template Name
    type: string
    default: todo-nodejs-mongo
  - name: templateBranch
    displayName: Template Branch
    type: string
    default: staging
  - name: subscriptionId
    displayName: subscription id
    type: string
  - name: location
    displayName: location
    type: string
    default: "eastus2"


variables:
  - name: templatePath
    value: template
  - name: ScriptPath
    value: script

jobs:
  - job: RunHooks
    steps:
      - task: Bash@3
        displayName: Install azd
        inputs:
          targetType: inline
          script: |

            curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --version daily


      - task: Bash@3
        displayName: Install template
        inputs:
          targetType: inline
          script: |

            azd config set auth.useAzCliAuth "true"
            azd config set defaults.subscription  ${{ parameters.subscriptionId }}
            azd config set defaults.location ${{ parameters.location }}


            mkdir -p $(templatePath)
            pushd $(templatePath)

            environmentName="sdkazdhook$(uuidgen | cut -c 1-6)"
            azd init -t ${{ parameters.templateName }} -b ${{ parameters.templateBranch }} -e $environmentName


      - task: Bash@3
        displayName: Replace azure.yaml file
        inputs:
          targetType: inline
          script: |

            yamlFile=$(cat $(ScriptPath)/azure.yaml)
            psFile=$(cat $(ScriptPath)/1.ps1)
            shFile=$(cat $(ScriptPath)/1.sh)

            pushd $(templatePath)


            # azure.yaml
            echo $yamlFile > azure.yaml

            # hooks file
            mkdir -p hooks
            pushd hooks
            echo $psFile > 1.ps1
            echo $shFile > 1.sh


      - task: Bash@3
        displayName: Show version
        inputs:
          targetType: inline
          script: |

            azd version

            ls
            pushd $(templatePath)
            ls
            cat azure.yaml
            pushd hooks
            cat 1.sh



      - task: AzureCLI@2
        displayName: Run azd hooks
        inputs:
          azureSubscription: tomServiceConnection1
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |

            # set -e



            pushd $(templatePath)

            chmod -R +x ./hooks/

            azd up --no-prompt
            
            azd down --purge --force


