name: Run azd hooks
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: templateName
    displayName: Template Name
    type: string
    default: todo-nodejs-mongo
  - name: templateBranch
    displayName: Template Name
    type: string
    default: pr/3976

variables:
  - name: templatePath
    value: template
  - name: ScriptPath
    value: script

jobs:
  - job: RunHooks
    steps:
      - task: Bash@3
        displayName: Install azd
        inputs:
          targetType: inline
          script: |

            # test 
            ls

            # 可能会要求输入密码 sudo
            curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --version daily

            azd version

            azd config set auth.useAzCliAuth "true"

            # test
            azd config show


            azd config set defaults.subscription "faa080af-c1d8-40ad-9cce-e1a450ca5b57"
            azd config set defaults.location eastus2

            # test
            azd config show


      - task: Bash@3
        displayName: Install template
        inputs:
          targetType: inline
          script: |
            mkdir -p $(templatePath)
            pushd $(templatePath)

            environmentName="sdkazdhook$(uuidgen | cut -c 1-6)"
            azd init -t ${{ parameters.templateName }} -b ${{ parameters.templateBranch }} -e $environmentName

            popd

      - task: Bash@3
        displayName: Replace azure.yaml file
        inputs:
          targetType: inline
          script: |

            yamlFile=$(cat $(ScriptPath)/azure.yaml)
            psFile=$(cat $(ScriptPath)/1.ps1)
            shFile=$(cat $(ScriptPath)/1.sh)

            pushd $(templatePath)


            # azure.yaml
            echo $yamlFile > azure.yaml

            # hooks file
            mkdir -p hooks
            pushd hooks
            echo $psFile > 1.ps1
            echo $shFile > 1.sh

            popd
            popd

      - task: AzureCLI@2
        displayName: Run azd hooks
        inputs:
          azureSubscription: test-connection
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # test
            azd config show

            pushd $(templatePath)

            azd up --no-prompt
            
            # test
            azd package 
            azd restore

            sleep 10

            azd down --purge --force


            popd

      - task: Bash@3
        displayName: Run azd hooks test
        inputs:
          targetType: inline
          script: |

            azd config show

            pushd $(templatePath)

            azd up --no-prompt

            sleep 10

            azd down --purge --force


            popd
